services:
  mqtt:
    image: eclipse-mosquitto
    container_name: herd_mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./infra/mosquitto/data:/mosquitto/data
      - ./infra/mosquitto/log:/mosquitto/log

  redis:
    image: redis:7
    container_name: herd_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: herd_postgres
    environment:
      POSTGRES_USER: herd
      POSTGRES_PASSWORD: herd123
      POSTGRES_DB: herdmind
    ports:
      - "5432:5432"

  influxdb:
    image: influxdb:2.7
    container_name: herd_influx
    ports:
      - "8086:8086"
    volumes:
      - ./infra/influxdb/data:/var/lib/influxdb2
      - ./infra/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=herdmind
      - DOCKER_INFLUXDB_INIT_PASSWORD=herdmindpassword123
      - DOCKER_INFLUXDB_INIT_ORG=herdmind
      - DOCKER_INFLUXDB_INIT_BUCKET=herd_telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=cfuR3oHFeBlAbbiIxas5OcXhTY3CZxkz1_QNkAlVrCu48Y6osB-loG7UcGvP1RlN1lRugY7qsAPgHZiu3JteEA==

  grafana:
    image: grafana/grafana:latest
    container_name: herd_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword123
    depends_on:
      - influxdb

  edge:
    build: ./edge
    container_name: herd_edge
    depends_on:
      - mqtt

  ai_service:
    build: ./services/ai_service
    container_name: herd_ai_service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mqtt
      - postgres
      - influxdb

  risk_service:
    build: ./services/risk_service
    container_name: herd_risk_service
    depends_on:
      - mqtt
      - postgres

  alert_service:
    build: ./services/alert_service
    container_name: herd_alert_service
    depends_on:
      - mqtt

  gateway:
    build: ./services/gateway_service
    container_name: herd_gateway
    ports:
      - "8000:8000"
    depends_on:
      - mqtt
      - redis
